name: malwatcher
services:
  worker:
    container_name: malwatcher-worker
    build:
      context: ./worker/
      dockerfile: Dockerfile
    # Change `always` to `build` to build from local source
    pull_policy: always 
    image: ghcr.io/r4z1xx/malwatcher-api:latest
    
    volumes:
      - ./worker/logs:/worker/logs
      - ./config:/worker/config
    networks:
      - malwatcher-network
  frontend:
    container_name: malwatcher-frontend
    image: ghcr.io/r4z1xx/malwatcher-front:latest
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    # Change `always` to `build` to build from local source
    pull_policy: always 
    ports:
      - 5000:5000
    volumes:
      - ./config:/app/config
    networks:
      - malwatcher-network
    depends_on:
      - worker

networks:
  malwatcher-network: