name: malwatcher
services:
  worker:
    container_name: malwatcher-worker
    image: ghcr.io/r4z1xx/malwatcher-api:latest
    # build:
    #   context: ./worker/
    #   dockerfile: Dockerfile
    volumes:
      - ./worker/logs:/worker/logs
      - ./config:/worker/config
    networks:
      - malwatcher-network
  frontend:
    container_name: malwatcher-frontend
    image: ghcr.io/r4z1xx/malwatcher-front:latest
    # build:
    #   context: ./frontend/
    #   dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./config:/app/config
    networks:
      - malwatcher-network
    depends_on:
      - worker

networks:
  malwatcher-network: