[modules]
    [modules.virustotal-api]
        # Your API key for VirusTotal
        vt-key = "" # Leave empty to not use it
    [modules.abuseipdb-api]
        # Your API key for AbuseIPDB
        abuseipdb-key = "" # Leave empty to not use it
    [modules.triage-api]
        # Your API key for Triage
        triage-key = "" # Leave empty to not use it
    [modules.polyswarm-api]
        # Your API key for Polyswarm
        polyswarm-key = "" # Leave empty to not use it
    [modules.otx-api]
        # Your API key for AlienVault OTX (NOT REQUIRED)
        otx-key = "" # Works without API key
    [modules.inquest-api]
        # Your API key for InQuest (NOT REQUIRED)
        inquest-key = "" # Works without API key

[settings]
    # Display the settings page on the web interface, default: true
    display = true # Set to false to hide the settings page

[logging]
    # Default: info => "debug" for debugging logs
    log-level = "info"

    # Log file path
    log-file = "/worker/logs/malwatcher.log"

[worker]
    # Protocol of the worker
    worker-protocol = "http"

    # Name or IP of the worker
    worker-name = "worker"

    # Port of the worker
    worker-port = 8080