name: Deploy Malwatcher images to ghcr.io

on: workflow_dispatch
# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

jobs:
  push-front-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './frontend'
    steps:
      - name: 'Checkout GA'
        uses: actions/checkout@v4

      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build malwatcher-front image'
        run: |
          username=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build . --tag ghcr.io/$username/malwatcher-front:latest
          docker push ghcr.io/$username/malwatcher-front:latest

  push-worker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './worker'
    steps:
      - name: 'Checkout GA'
        uses: actions/checkout@v4

      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build malwatcher-api image'
        run: |
          username=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          docker build . --tag ghcr.io/$username/malwatcher-api:latest
          docker push ghcr.io/$username/malwatcher-api:latest
