name: Deploy Malwatcher images to ghcr.io

on:
#   push:
#     branches:
#       - main
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

jobs:
  push-front-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './frontend'
    steps:
      - name: 'Checkout GA'
        uses: actions/checkout@v4

      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build malwatcher-front image'
        run: |
          username=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          # Build with both version and latest tags
          docker build . \
            --tag ghcr.io/$username/malwatcher-front:${{ github.event.inputs.version }} \
            --tag ghcr.io/$username/malwatcher-front:latest
          # Push both tags
          docker push ghcr.io/$username/malwatcher-front:${{ github.event.inputs.version }}
          docker push ghcr.io/$username/malwatcher-front:latest

  push-worker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './worker'
    steps:
      - name: 'Checkout GA'
        uses: actions/checkout@v4

      - name: 'Login to GHCR'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build malwatcher-api image'
        run: |
          username=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          # Build with both version and latest tags
          docker build . \
            --tag ghcr.io/$username/malwatcher-api:${{ github.event.inputs.version }} \
            --tag ghcr.io/$username/malwatcher-api:latest
          # Push both tags
          docker push ghcr.io/$username/malwatcher-api:${{ github.event.inputs.version }}
          docker push ghcr.io/$username/malwatcher-api:latest
